apiVersion: v1
kind: Pod
metadata:
  name: nodejs-database-app
  labels:
    name: nodejs-database-app
spec:
  containers:
  - name: nodejs-database-app
    image: nodejs-testapp
    command: ["node main.js; sleep 9800"]
    env:
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: mysql-user
      - name: MYSQL_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: mysql-root-pw
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
